'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const tools=require('../frontend/js/btmh_catalogs.js');
const settle=async()=>{for(let i=0;i<20;i++)await Promise.resolve();};
const buttons=el=>[...(el.tagName==='BUTTON'?[el]:[]),...(el.children||[]).flatMap(buttons)];
const click=el=>el.dispatchEvent(new Event('click'));
async function catalogLoaded(w,zones=[]){w.requests[0].resolve({items:[{id:7,store_code:'QA',store_name:'Test Store',timezone_name:'UTC',status:'ACTIVE'}]});w.requests[1].resolve({items:[]});w.requests[2].resolve({available:true,items:zones});await settle();}
test('zone names are scoped by stable store ID and duplicate camera rows do not inflate counts',()=>{const rows=tools.zoneRows([{id:1,store_id:4,store_name:'A',zone_name:'Quầy',camera_name:'One'},{id:1,store_id:4,store_name:'A',zone_name:'Quầy',camera_name:'One'},{id:2,store_id:5,store_name:'A',zone_name:'Quầy',camera_name:'Two'},{id:3,store_id:4,zone_name:''}]);assert.equal(rows.length,2);assert.equal(rows.every(row=>row.cameras.length===1),true);assert.deepEqual(rows.map(row=>row.storeId).sort(),[4,5]);});
test('catalog data allowlist drops credentials and distinguishes unknown camera count from zero',()=>{const rows=tools.storeRows([{id:1,store_name:'Cửa hàng',source:'private',password:'private',status:'ACTIVE'}],null);assert.equal(rows[0].cameras,'—');assert.equal(JSON.stringify(rows).includes('private'),false);assert.equal(tools.storeRows([{id:1}],[])[0].cameras,0);assert.equal(JSON.stringify(tools.zoneRows([{id:1,zone_name:'rtsp://user:pass@host/path',source:'private'}])).includes('user:pass'),false);});
test('create payload validates names/timezone and successful HTTP alone is not a save acknowledgment',()=>{assert.deepEqual(tools.storePayload(' ab ','Cửa hàng','Asia/Ho_Chi_Minh'),{store_code:'AB',store_name:'Cửa hàng',timezone_name:'Asia/Ho_Chi_Minh'});assert.throws(()=>tools.storePayload('AB','Cửa hàng','not-a-zone'));assert.throws(()=>tools.storePayload('AB','rtsp://user:pass@host','UTC'));assert.equal(tools.saveConfirmed({ok:true}),false);assert.equal(tools.saveConfirmed({ok:true,store:{id:0}}),false);assert.equal(tools.saveConfirmed({ok:true,store:{id:2}}),true);});
test('catalog request owner rejects stale response, logout actor and off-page races',async()=>{let allowed=true,user={id:1};const requests=[],delivered=[];const reader=tools.createReader({eligible:()=>allowed,actor:()=>user,request:signal=>new Promise(resolve=>requests.push({signal,resolve})),success:data=>delivered.push(data),error:()=>assert.fail()});void reader.refresh();void reader.refresh();assert.equal(requests[0].signal.aborted,true);requests[1].resolve('new');requests[0].resolve('old');await settle();assert.deepEqual(delivered,['new']);void reader.refresh();user={id:2};requests[2].resolve('private');await settle();assert.deepEqual(delivered,['new']);void reader.refresh();allowed=false;requests[3].resolve('private');await settle();assert.deepEqual(delivered,['new']);reader.stop();});
test('reader stop cancels browser work and error can be retried without a timer or worker operation',async()=>{const requests=[],errors=[],delivered=[];const reader=tools.createReader({eligible:()=>true,actor:()=>null,request:signal=>new Promise((resolve,reject)=>requests.push({signal,resolve,reject})),success:data=>delivered.push(data),error:reason=>errors.push(reason)});void reader.refresh();reader.stop();assert.equal(requests[0].signal.aborted,true);requests[0].resolve('late');await settle();assert.deepEqual(delivered,[]);void reader.refresh();requests[1].reject(new Error('offline'));await settle();assert.equal(errors.length,1);void reader.refresh();requests[2].resolve('real');await settle();assert.deepEqual(delivered,['real']);});
function browser(){
  class Element extends EventTarget{constructor(tag='div'){super();this.tagName=tag.toUpperCase();this.children=[];this.dataset={};this.attributes={};this.value='';this.hidden=false;this.disabled=false;this.className='';this._text='';}set textContent(text){this._text=String(text);this.children=[];}get textContent(){return this._text+this.children.map(child=>child.textContent).join(' ');}append(...children){this.children.push(...children);}replaceChildren(...children){this.children=children;this._text='';}setAttribute(key,value){this.attributes[key]=String(value);}get options(){return this.children;}focus(){document.activeElement=this;}reset(){if(this.id==='catalogZoneForm'){document.getElementById('catalogZoneName').value='';document.getElementById('catalogZoneStatus').value='ACTIVE';return;}roots.get('catalogStoreCode').value='';roots.get('catalogStoreName').value='';roots.get('catalogStoreTimezone').value='Asia/Ho_Chi_Minh';}}
  const document=new EventTarget(),window=new EventTarget(),roots=new Map(),requests=[],calls=[],state={authUser:{id:1}};let allowed=true,manage=true;
  document.hidden=false;document.createElement=tag=>new Element(tag);document.getElementById=id=>{if(!roots.has(id)){const el=new Element();el.id=id;roots.set(id,el);}return roots.get(id);};
  const page=document.getElementById('page-ops-center');page.classList={contains:()=>allowed};
  const tabs=['stores','zones','cameras'].map(name=>{const el=document.getElementById('catalogTab'+name[0].toUpperCase()+name.slice(1));el.dataset.catalogTab=name;return el;});document.querySelectorAll=selector=>selector==='[data-catalog-tab]'?tabs:[];document.getElementById('catalogStoreForm').hidden=true;
  window.confirm=()=>true;window.document=document;window.BTMHCameraConfiguration={start:()=>calls.push('start-camera'),stop:()=>calls.push('stop-camera'),refresh:()=>calls.push('refresh-camera')};
  class CustomEvent extends Event{constructor(name,{detail}={}){super(name);this.detail=detail;}}
  const context=vm.createContext({window,document,state,AbortController,Intl,CustomEvent,appPresentationActive:()=>!!state.authUser,hasUiPermission:key=>!!state.authUser&&(key!=='system.manage'||manage),api:(url,options={})=>new Promise((resolve,reject)=>requests.push({url,options,resolve,reject}))});vm.runInContext(fs.readFileSync(require.resolve('../frontend/js/btmh_catalogs.js'),'utf8'),context);
  return {document,window,roots,requests,calls,state,allow:value=>{allowed=value;},manage:value=>{manage=value;},get:id=>document.getElementById(id)};
}
test('store editor sends PATCH to stable ID and preserves unconfirmed draft',async()=>{const w=browser();await catalogLoaded(w);click(buttons(w.get('catalogStoreList')).find(el=>el.textContent==='Sửa'));assert.equal(w.get('catalogStoreName').value,'Test Store');w.get('catalogStoreName').value='Updated';w.get('catalogStoreStatus').value='ARCHIVED';w.get('catalogStoreForm').dispatchEvent(new Event('submit',{cancelable:true}));const req=w.requests[3];assert.equal(req.url,'/api/v1/stores/7');assert.equal(req.options.method,'PATCH');assert.equal(JSON.parse(req.options.body).status,'ARCHIVED');req.reject({status:409});await settle();assert.equal(w.get('catalogStoreForm').hidden,false);assert.equal(w.get('catalogStoreName').value,'Updated');assert.match(w.get('catalogStoreSaveNote').textContent,/liên kết/);});
test('zone create is gated by schema availability and requires entity acknowledgment',async()=>{const w=browser();await catalogLoaded(w);w.window.BTMHCatalogs.selectTab('zones');for(const req of w.requests.slice(3))req.resolve(req.url==='/api/v1/zones'?{available:true,items:[]}:{items:[]});await settle();click(w.get('catalogAddZone'));w.get('catalogZoneFormStore').value='7';w.get('catalogZoneName').value='Desk';w.get('catalogZoneForm').dispatchEvent(new Event('submit',{cancelable:true}));const req=w.requests.at(-1);assert.equal(req.url,'/api/v1/zones');assert.equal(req.options.method,'POST');assert.deepEqual(JSON.parse(req.options.body),{store_id:7,zone_name:'Desk'});req.resolve({ok:true});await settle();assert.equal(w.get('catalogZoneForm').hidden,false);assert.match(w.get('catalogZoneSaveNote').textContent,/Chưa xác nhận/);w.state.authUser=null;w.window.BTMHCatalogs.stop(true);assert.equal(w.get('catalogZoneForm').hidden,true);assert.equal(w.get('catalogZoneName').value,'');});
test('zone entity counts and deletion affordance retain reference protections',async()=>{const w=browser();await catalogLoaded(w,[{id:2,store_id:7,store_name:'Test Store',zone_name:'Used',status:'ACTIVE',ever_assigned:1,camera_count:0},{id:3,store_id:7,store_name:'Test Store',zone_name:'Fresh',status:'ACTIVE',ever_assigned:0,camera_count:0}]);const rendered=buttons(w.get('catalogZoneList'));assert.equal(rendered.filter(button=>button.textContent==='Xóa').length,1);assert.equal(tools.itemConfirmed({ok:true,item:{id:3}},2),false);assert.equal(tools.itemConfirmed({ok:true,item:{id:3}},3),true);const rows=tools.entityZones([{id:2,store_id:7,camera_count:0,ever_assigned:1,source:'private'}],null);assert.equal(rows[0].count,0);assert.equal(JSON.stringify(rows).includes('private'),false);});
test('store/zone tabs do not open camera media; keyboard camera tab starts only existing editor',async()=>{const w=browser();assert.deepEqual(w.requests.map(row=>row.url),['/api/v1/stores','/api/v1/recognition/cameras','/api/v1/zones']);assert.equal(w.calls.includes('start-camera'),false);w.requests.forEach(row=>row.resolve({items:[]}));await settle();w.window.BTMHCatalogs.selectTab('cameras',true);assert.equal(w.get('catalogCameraPanel').hidden,false);assert.equal(w.get('catalogTabCameras').attributes['aria-selected'],'true');assert.equal(w.calls.filter(name=>name==='start-camera').length,1);w.window.BTMHCatalogs.selectTab('zones');assert.equal(w.get('catalogCameraPanel').hidden,true);assert.equal(w.calls.at(-1),'stop-camera');w.window.BTMHCatalogs.stop();});
test('catalog logout cancels requests, erases scoped rows and resets unsubmitted store details',async()=>{const w=browser();w.get('catalogStoreName').value='Private draft';w.window.BTMHCatalogs.stop(true);assert.equal(w.requests.every(row=>row.options.signal.aborted),true);w.requests.forEach(row=>row.resolve({items:[{id:2,store_name:'Private late'}]}));await settle();assert.equal(w.get('catalogStoreList').textContent.includes('Private'),false);assert.equal(w.get('catalogStoreName').value,'');});
test('store save rejects missing acknowledgment and permission; repeated submits share one request',async()=>{const w=browser();w.requests.forEach(row=>row.resolve({items:[]}));await settle();w.get('catalogStoreCode').value='AB';w.get('catalogStoreName').value='Cửa hàng';w.get('catalogStoreTimezone').value='UTC';w.manage(false);w.get('catalogStoreForm').dispatchEvent(new Event('submit',{cancelable:true}));assert.equal(w.requests.length,3);w.manage(true);w.get('catalogStoreForm').hidden=false;w.get('catalogStoreForm').dispatchEvent(new Event('submit',{cancelable:true}));w.get('catalogStoreForm').dispatchEvent(new Event('submit',{cancelable:true}));assert.equal(w.requests.length,4);assert.equal(w.requests[3].url,'/api/v1/stores');assert.equal(w.requests[3].options.method,'POST');assert.equal(w.get('catalogStoreSave').disabled,true);w.requests[3].resolve({ok:true});await settle();assert.match(w.get('catalogStoreSaveNote').textContent,/Chưa xác nhận/);assert.equal(w.get('catalogStoreForm').hidden,false);assert.equal(w.get('catalogStoreSave').disabled,false);});
