@echo off
setlocal EnableExtensions
rem Reject inherited preview profiles before any config/data/process mutation.
if "%BTMH_UI_PREVIEW%"=="1" (
  echo [ERROR] UI_PREVIEW cannot use the production or development runtime launcher.
  echo [ACTION] Close the preview shell and launch BTMH from a normal terminal.
  exit /b 7
)
rem Keep the verified installed source payload free of generated bytecode.
set "PYTHONDONTWRITEBYTECODE=1"
rem Direct launches are production, including shells with an inherited DEV env.
rem The dedicated DEV wrapper passes this explicit invocation selector and uses
rem the existing BTMH_ENV configuration for every child/check/backend process.
set "BTMH_ENV=production"
if /i "%~1"=="--development" set "BTMH_ENV=development"
if /i "%BTMH_ENV%"=="development" (
  echo [MODE] DEVELOPMENT
) else (
  echo [MODE] PRODUCTION
)
if not defined BTMH_NETWORK_MODE set "BTMH_NETWORK_MODE=local"
cd /d "%~dp0"
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0scripts\check_standard_user.ps1"
if errorlevel 1 (
  pause
  exit /b 5
)

rem ============================================================
rem Bao Tin Manh Hai launcher (production default; development is explicit)
rem - one private per-user runtime under %%LOCALAPPDATA%%\CampusFace
rem - PostgreSQL direct-start supervisor with hard timeout
rem - automatic local port recovery
rem - no infinite wait
rem ============================================================

call "%~dp0scripts\resolve_data_root.bat"
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0scripts\stop_stale_campusface.ps1"
if errorlevel 1 (
  echo [ERROR] Could not stop an old BTMH Face web process safely.
  pause
  exit /b 9
)

set "PY=%CAMPUSFACE_DATA_ROOT%\runtime\venv\Scripts\python.exe"
if /i "%BTMH_ENV%"=="development" if defined BTMH_DEV_PYTHON set "PY=%BTMH_DEV_PYTHON%"
set "PG_ENV=%CAMPUSFACE_DATA_ROOT%\config\postgres_runtime_env.bat"
if not defined MODULE_HOST set "MODULE_HOST=127.0.0.1"
if not exist "%PY%" (
  echo ============================================================
  echo [ERROR] BTMH Face runtime is not installed for this Windows user.
  echo [ACTION] Run the top-level INSTALL_NEW_PC.bat once.
  echo ============================================================
  pause
  exit /b 2
)

"%PY%" scripts\apply_pro_r2_config.py >nul 2>nul
"%PY%" scripts\apply_camera_hd_v5_config.py >nul 2>nul
"%PY%" scripts\apply_v27_performance_config.py >nul 2>nul
if errorlevel 1 echo [WARN] Performance migration was skipped; existing settings remain.
"%PY%" scripts\apply_v291_realtime_hotfix.py >nul 2>nul
if errorlevel 1 echo [WARN] Realtime migration was skipped; existing settings remain.
"%PY%" scripts\check_v28_media_runtime.py >nul 2>nul
if errorlevel 1 echo [INFO] Python WebRTC fallback is unavailable; native gateway remains primary.
"%PY%" scripts\check_mediamtx_runtime.py
if errorlevel 1 (
  if /i "%BTMH_ENV%"=="development" (
    echo [ERROR] Development media preflight failed unexpectedly.
  ) else (
    echo [ERROR] Production requires a verified supported MediaMTX gateway.
  )
  echo [ACTION] Install the pinned local ZIP with scripts\install_mediamtx_offline.ps1.
  pause
  exit /b 6
)

echo.
echo [1/3] Starting/verifying local PostgreSQL...
echo [INFO] PostgreSQL uses a direct process supervisor with a hard 30-second start timeout.
"%PY%" -u scripts\postgres_guard.py ensure
set "PG_RC=%ERRORLEVEL%"
if "%PG_RC%"=="87" goto :pg_win487
if "%PG_RC%"=="0" goto :validate_pg
rem Labels keep error codes current without delayed expansion of secret values.
echo [INFO] PostgreSQL is not initialized or needs repair. Running one repair pass...
call SETUP_POSTGRESQL_WINDOWS.bat
set "PG_SETUP_RC=%ERRORLEVEL%"
if "%PG_SETUP_RC%"=="87" goto :pg_win487
if not "%PG_SETUP_RC%"=="0" goto :pg_failed
"%PY%" -u scripts\postgres_guard.py ensure
set "PG_RC=%ERRORLEVEL%"
if "%PG_RC%"=="87" goto :pg_win487
if not "%PG_RC%"=="0" goto :pg_failed

:validate_pg
if exist "%PG_ENV%" call "%PG_ENV%"
"%PY%" scripts\check_postgres.py >nul 2>nul
if not errorlevel 1 goto :after_pg_validation
echo [WARN] PostgreSQL is running but application database login validation failed.
echo [INFO] Running one credential-safe repair pass...
call SETUP_POSTGRESQL_WINDOWS.bat
if errorlevel 1 goto :pg_failed
if exist "%PG_ENV%" call "%PG_ENV%"
"%PY%" scripts\check_postgres.py >nul 2>nul
if errorlevel 1 goto :pg_failed

:after_pg_validation
echo.
echo [2/3] Verifying AI/runtime readiness...
"%PY%" scripts\check_ready.py
if errorlevel 1 (
  echo [ERROR] BTMH readiness validation failed.
  echo [ACTION] Read the [ERROR] line above. Run INSTALL_NEW_PC.bat only when a runtime/model component is actually missing.
  pause
  exit /b 3
)

echo.
echo [3/3] Starting BTMH Face web server...
echo ============================================================
echo BAO TIN MANH HAI - DANG KHOI DONG MAY CHU
if defined CAMPUSFACE_POSTGRES_PORT echo PostgreSQL: 127.0.0.1:%CAMPUSFACE_POSTGRES_PORT%
echo The verified web URL appears after backend startup and socket binding succeed.
echo Data: %CAMPUSFACE_DATA_ROOT%
echo Keep this window open. Press Ctrl+C to stop the web server.
echo ============================================================
set "BTMH_OPEN_BROWSER=1"
"%PY%" run_module.py
set "APP_RC=%ERRORLEVEL%"
echo.
echo [INFO] BTMH Face server exited with code %APP_RC%.
pause
exit /b %APP_RC%

:pg_win487
echo.
echo ============================================================
echo [PG-WIN-487] Windows shared-memory compatibility issue detected.
echo [INFO] BTMH will request Administrator approval to apply a
echo        Bottom-up ASLR override ONLY to its private postgres.exe.
echo ============================================================
call scripts\repair_postgres_windows_487.bat
if errorlevel 1 goto :pg_failed
echo [PG] Retrying PostgreSQL after Windows compatibility repair...
"%PY%" -u scripts\postgres_guard.py ensure
if errorlevel 1 goto :pg_failed
goto :pg_ready_after_487

:pg_ready_after_487
if exist "%PG_ENV%" call "%PG_ENV%"
"%PY%" scripts\check_postgres.py >nul 2>nul
if errorlevel 1 goto :pg_failed
goto :after_pg_validation


:pg_failed
echo.
echo ============================================================
echo [ERROR] Local PostgreSQL could not be repaired automatically.
echo [LOG] %CAMPUSFACE_DATA_ROOT%\logs\postgres-runtime.log
echo [LOG] %CAMPUSFACE_DATA_ROOT%\logs\postgres-install.log
echo [TOOL] Run: 03_TOOLS_DIAGNOSTIC\FULL_SYSTEM_DIAGNOSTIC.bat
echo ============================================================
pause
exit /b 4
