const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let historyMode='hr', pollTimer=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const dt=v=>{if(!v)return '—';try{return new Date(v).toLocaleString('vi-VN',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'});}catch{return String(v)}};
async function api(url,opt={}){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d}
function setAuthenticated(ok){$('#loginGate').classList.toggle('hidden',ok);$('#appShell').classList.toggle('hidden',!ok);if(ok){mountStreams();refreshAll();startPolling();}else{stopPolling();$$('[data-mobile-stream]').forEach(x=>x.removeAttribute('src'));}}
async function authStatus(){try{const s=await api('/api/v1/mobile/auth/status');setAuthenticated(!!s.authenticated);if(!s.enabled&&!s.authenticated)$('#loginNote').textContent=s.configured?'Mobile Viewer đang bị Admin tắt.':'Admin chưa cấu hình Mobile Viewer.';}catch(e){$('#loginNote').textContent=e.message;setAuthenticated(false)}}
async function login(){const b=$('#mobileLogin');b.disabled=true;try{await api('/api/v1/mobile/auth/login',{method:'POST',body:JSON.stringify({password:$('#mobilePassword').value})});$('#mobilePassword').value='';$('#loginNote').textContent='';setAuthenticated(true);}catch(e){$('#loginNote').textContent=e.message}finally{b.disabled=false}}
async function logout(){try{await api('/api/v1/mobile/auth/logout',{method:'POST'})}catch{}setAuthenticated(false)}
function mountStreams(){const url=`/api/v1/mobile/camera/stream.mjpg?t=${Date.now()}`;$$('[data-mobile-stream]').forEach(img=>{if(img.src!==url)img.src=url})}
function initials(n=''){const p=String(n).trim().split(/\s+/).filter(Boolean);return ((p[0]?.[0]||'?')+(p.length>1?(p.at(-1)?.[0]||''):'')).toUpperCase()}
function renderPeople(host,items){host.innerHTML=items.length?items.map(x=>`<div class="person-row"><div class="avatar">${esc(initials(x.full_name))}</div><div><b>${esc(x.full_name)}</b><small>${esc(x.department||x.group||x.employee_code||'Nhân viên')}</small></div><time>${esc(dt(x.last_seen_at||x.started_at))}</time></div>`).join(''):'<div class="empty">Chưa có nhân viên đang hiện diện.</div>'}
async function loadSummary(){try{const d=await api('/api/v1/mobile/summary');$('#kpiEmployees').textContent=d.employees;$('#kpiPresent').textContent=d.present;$('#kpiFace').textContent=d.faceid_enrolled;$('#kpiCamera').textContent=d.camera.online?'ONLINE':'OFFLINE';$('#homeCameraName').textContent=d.camera.label||'Camera văn phòng';$('#homeCameraState').textContent=d.camera.online?'ONLINE':'OFFLINE';$('#homeCameraState').className='state '+(d.camera.online?'online':'');$('#homeCameraMeta').textContent=`${d.camera.resolution||'—'} · ${d.camera.fps||0} FPS`;$('#cameraMeta').textContent=`${d.camera.label||'Camera'} · ${d.camera.resolution||'—'} · Mobile preview ~10 FPS`; }catch(e){if(e.message.includes('đăng nhập'))setAuthenticated(false)}}
async function loadPresence(){try{const d=await api('/api/v1/mobile/presence'),items=d.items||[];renderPeople($('#homePresence'),items.slice(0,5));renderPeople($('#presenceList'),items);$('#presentCount').textContent=`${items.length} người`;}catch(e){if(e.message.includes('đăng nhập'))setAuthenticated(false)}}
async function loadCameras(){try{const d=await api('/api/v1/mobile/cameras'),items=d.items||[];$('#cameraList').innerHTML=items.map(x=>`<div class="camera-item"><div><b>${esc(x.name)}</b><small>${esc(x.zone|| (x.active?'Camera đang dùng':'Camera dự phòng'))}</small></div><i class="dot ${x.status==='ONLINE'?'online':''}"></i></div>`).join('')||'<div class="empty">Chưa có camera.</div>';}catch{}}
const hrLabel=t=>({PRESENT:'Có mặt',ENTERED:'Vào văn phòng',RETURNED:'Quay lại',OUT:'Ra ngoài',EXITED:'Ra ngoài',TEMP_LOST:'Tạm mất theo dõi',STATUS_CHANGED:'Đổi trạng thái'}[String(t||'').toUpperCase()]||String(t||'Sự kiện'));
const recLabel=t=>({RECOGNIZED:'Nhận diện thành công',SPOOF_BLOCKED:'Giả mạo bị chặn',UNREGISTERED:'Chưa đăng ký',RECOGNITION_REVIEW:'Cần xác minh'}[String(t||'').toUpperCase()]||String(t||'Nhận diện'));
async function loadHistory(){const host=$('#historyList');try{const d=await api(historyMode==='hr'?'/api/v1/mobile/history/hr?limit=80':'/api/v1/mobile/history/recognition?limit=80'),items=d.items||[];host.innerHTML=items.length?items.map(x=>`<div class="event"><div><b>${esc(x.full_name||'Chưa xác định')}</b><small>${esc(x.employee_code||'')} ${esc(x.reason||'')}</small><span class="tag">${esc(historyMode==='hr'?hrLabel(x.event_type):recLabel(x.event_type))}${x.repeat_count>1?` · ×${x.repeat_count}`:''}</span></div><time>${esc(dt(x.event_at))}</time></div>`).join(''):'<div class="empty">Chưa có sự kiện.</div>';}catch(e){host.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
async function refreshAll(){await Promise.all([loadSummary(),loadPresence(),loadCameras(),loadHistory()])}
function startPolling(){stopPolling();pollTimer=setInterval(()=>{loadSummary();loadPresence();if($('[data-screen="history"]').classList.contains('active'))loadHistory()},5000)}function stopPolling(){if(pollTimer)clearInterval(pollTimer);pollTimer=null}
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>{$$('[data-nav]').forEach(x=>x.classList.toggle('active',x===b));$$('.screen').forEach(x=>x.classList.toggle('active',x.dataset.screen===b.dataset.nav));if(b.dataset.nav==='camera'){mountStreams();loadCameras()}if(b.dataset.nav==='history')loadHistory();if(b.dataset.nav==='presence')loadPresence()}));
$$('[data-history]').forEach(b=>b.addEventListener('click',()=>{historyMode=b.dataset.history;$$('[data-history]').forEach(x=>x.classList.toggle('active',x===b));loadHistory()}));
$('#mobileLogin').addEventListener('click',login);$('#mobilePassword').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('#mobileLogout').addEventListener('click',logout);$('#refreshHome').addEventListener('click',()=>Promise.all([loadSummary(),loadPresence()]));$('#refreshPresence').addEventListener('click',loadPresence);$('#refreshHistory').addEventListener('click',loadHistory);
if('serviceWorker'in navigator){navigator.serviceWorker.register('/mobile/sw.js',{scope:'/mobile'}).catch(()=>{})}authStatus();